export {default as Home} from "./Home"
export {default as Projects} from "./Projects"
export {default as Experiences} from "./Experiences"
export {default as Contact} from "./Contact"
export {default as Misc} from "./Misc"